# -*- coding: utf-8 -*-
"""NPV Calculator (Session 01)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLgJeKk_Rbrp5TuirFYcSrKpzHvP7i7i
"""

cash_flows = [10000, 15000, -5000, 20000, 30000]
rate = 0.073
initial_investment = 50000

npv = 0
year = 1   # start from year 1

for cash in cash_flows:
    npv += cash / (1 + rate) ** year
    year += 1   # move to next year

npv -= initial_investment

print("NPV =", round(npv, 2))

# Step 1: User input
initial_investment = float(input("Enter initial investment: "))
rate = float(input("Enter discount rate (e.g. 0.073): "))
years = int(input("Enter number of years: "))

# Step 2: Input cash flows
cash_flows = []
for i in range(years):
    cash = float(input(f"Enter cash flow for year {i+1}: "))
    cash_flows.append(cash)

# Step 3: NPV function
def calculate_npv(cash_flows, rate, initial_investment):
    npv = 0
    year = 1
    for cash in cash_flows:
        npv += cash / (1 + rate) ** year
        year += 1
    return npv - initial_investment

# Step 4: Scenarios
base_case = cash_flows
best_case = [cash * 1.2 for cash in cash_flows]
worst_case = [cash * 0.8 for cash in cash_flows]

scenarios = {
    "Base Case": base_case,
    "Best Case": best_case,
    "Worst Case": worst_case
}

# Step 5: Results
print("\n--- Scenario Analysis ---")

for name, flows in scenarios.items():
    npv = calculate_npv(flows, rate, initial_investment)
    print(f"{name} NPV: {round(npv, 2)}")

    if npv > 0:
        print("→ Good investment ✅\n")
    else:
        print("→ Not a good investment ❌\n")

# Step 1: Take user input
initial_investment = float(input("Enter initial investment: "))
rate = float(input("Enter discount rate (e.g. 0.073): "))
years = int(input("Enter number of years: "))

# Step 2: Take cash flows input
cash_flows = []
for i in range(years):
    cash = float(input(f"Enter cash flow for year {i+1}: "))
    cash_flows.append(cash)

# Step 3: Create scenarios
base_case = cash_flows
best_case = [cash * 1.2 for cash in cash_flows]   # +20%
worst_case = [cash * 0.8 for cash in cash_flows]  # -20%

scenarios = {
    "Base Case": base_case,
    "Best Case": best_case,
    "Worst Case": worst_case
}

# Step 4: Detailed NPV function
def calculate_npv_detailed(cash_flows, rate, initial_investment, scenario_name):
    print(f"\n=== {scenario_name} ===")
    print("Year | Cash Flow | Discounted Value")
    print("-----------------------------------")

    npv = 0
    year = 1

    for cash in cash_flows:
        discounted_value = cash / (1 + rate) ** year
        npv += discounted_value

        print(f"{year:<4} | {cash:<10} | {round(discounted_value, 2)}")
        year += 1

    print("-----------------------------------")
    print(f"Total PV of Cash Flows: {round(npv, 2)}")
    print(f"Initial Investment: {initial_investment}")

    final_npv = npv - initial_investment
    print(f"NPV: {round(final_npv, 2)}")

    if final_npv > 0:
        print("→ Good investment ✅")
    else:
        print("→ Not a good investment ❌")

    return final_npv

# Step 5: Run analysis
print("\n=========== SCENARIO ANALYSIS ===========")

results = {}

for name, flows in scenarios.items():
    npv = calculate_npv_detailed(flows, rate, initial_investment, name)
    results[name] = npv

# Step 6: Summary Comparison
print("\n=========== SUMMARY ===========")
print("Scenario       | NPV")
print("----------------------------")

for name, npv in results.items():
    print(f"{name:<13} | {round(npv, 2)}")

# Step 1: Take user input
initial_investment = float(input("Enter initial investment: "))
rate = float(input("Enter discount rate (e.g. 0.073): ")) # This 'rate' is for initial NPV, not directly used in IRR calculation below.
years = int(input("Enter number of years: "))

# Step 2: Take cash flows input
cash_flows = []
for i in range(years):
    cash = float(input(f"Enter cash flow for year {i+1}: "))
    cash_flows.append(cash)

# Define the calculate_npv function as it's a dependency for calculate_irr
def calculate_npv(cash_flows, rate, initial_investment):
    npv = 0
    year = 1
    for cash in cash_flows:
        npv += cash / (1 + rate) ** year
        year += 1
    return npv - initial_investment

# Define the calculate_irr function (moved out of the loop and properly indented)
def calculate_irr(cash_flows, initial_investment):
    low = 0.0
    high = 1.0   # 100%
    tolerance = 0.0001   # how close to 0 you want NPV for IRR

    # Iterate to find the IRR
    for i in range(1000):
        rate_guess = (low + high) / 2
        npv = calculate_npv(cash_flows, rate_guess, initial_investment)

        # print(f"Rate: {round(rate_guess,4)} \u2192 NPV: {round(npv,2)}") # Uncomment for debugging

        # Stop if NPV is very close to 0
        if abs(npv) < tolerance:
            return rate_guess

        # Adjust range
        if npv > 0:
            low = rate_guess
        else:
            high = rate_guess

    return rate_guess # Return the best guess found after iterations

# Example of how to use calculate_irr after collecting inputs
irr_value = calculate_irr(cash_flows, initial_investment)
print(f"\nCalculated IRR: {round(irr_value * 100, 2)}%")